Models/ErrorViewModel.cs
namespace UsuariosProductos.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Producto.cs
using System.ComponentModel.DataAnnotations;

namespace UsuariosProductos.Models;

public class Producto {
    public int Id { get; set; }
    [Required]
    public string ImagenURL { get; set; }
    [Required]
    public string Nombre { get; set; }
    [Required]    
    public string Descripcion { get; set; }
    [Required]    
    public double Precio { get; set; }
    [Required]
    public int Cantidad { get; set; }
    [Required]
    public DateTime FechaVencimiento { get; set; }
    [Required]
    public int UsuarioId { get; set; }
}

Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace UsuariosProductos.Models;

public class Usuario {
    public int Id { get; set; }
    [Required]
    public string Nombres { get; set; }
    [Required]
    public string Apellidos { get; set; }
    [Required]
    public string Correo { get; set; }
    [Required]
    public string Direccion { get; set; }
    [Required]
    public string Telefono { get; set; }
    [Required]
    public DateTime FechaNacimiento { get; set; }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using UsuariosProductos.Models;

namespace UsuariosProductos.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UsuariosProductos.Data;
using UsuariosProductos.Models;
using System.Linq.Expressions;
namespace UsuariosProductos.Controllers;

public class ProductosController : Controller {
    public readonly BaseContext _context;
    public ProductosController(BaseContext context) {
        _context = context;
    }
    public async Task<IActionResult> Index(string search) {
        var productos = from producto in _context.Productos select producto;
        if(!string.IsNullOrEmpty(search)){
            productos = productos.Where(p => p.Nombre.Contains(search));
            return View(await productos.ToListAsync());
        }
        return View(await productos.ToListAsync());
    }

    public async Task<IActionResult> Detalles(int id) {
        return View(await _context.Productos.FirstOrDefaultAsync(m => m.Id == id));
    }

    public IActionResult Crear(){
            return View();
    }

    [HttpPost]
    public async Task<IActionResult> Crear(Producto p){
        if(ModelState.IsValid){
            _context.Productos.Add(p);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(p); 
    }

    public async Task<IActionResult> Editar(int id){
       return View(await _context.Productos.FirstOrDefaultAsync(m => m.Id == id));
    }

    [HttpPost]
    public async Task<IActionResult> Editar(Producto p){
        if(ModelState.IsValid){
            _context.Productos.Update(p);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(p);
    }

    public async Task<IActionResult> Eliminar(int id) {
        //Buscamos en la base de datos
        var producto = await _context.Productos.FindAsync(id);
        //Elimina un objeto del DbSet Productos que está dentro del contexto de la base de datos
        _context.Productos.Remove(producto!);
        //Es responsable de guardar los cambios realizados en el contexto de la base de datos de forma asíncrona.       
        await _context.SaveChangesAsync();
        //Nos redirigimos a otra vista
        return RedirectToAction("Index");
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using UsuariosProductos.Data;
using UsuariosProductos.Models;
namespace UsuariosProductos.Controllers;

public class UsuariosController : Controller {
    public readonly BaseContext _context;
    public UsuariosController(BaseContext context) {
        _context = context;
    }
    public async Task<IActionResult> Index(string search) {
        var usuarios = from usuario in _context.Usuarios select usuario;
        if(!string.IsNullOrEmpty(search)){
            usuarios = usuarios.Where(m => m.Nombres.Equals(search));
            return View(await usuarios.ToListAsync());
        }
        return View(await usuarios.ToListAsync());
    }

    public async Task<IActionResult> Detalles(int id) {
        return View(await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == id));
    }

    public IActionResult Crear(){
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Crear(Usuario u){

        if(ModelState.IsValid){
        //Agregar el usuario al DbSet
        _context.Usuarios.Add(u);
        //Guardamos los cambios realizados en el contexto de la base de datos
        await _context.SaveChangesAsync();
        //Nos redirigimos a otra vista
        return RedirectToAction("Index");

        }else{
            return View(u);
        }
    }

    public async Task<IActionResult> Editar(int id){
        return View(await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == id));
    }

    [HttpPost]
    public async Task<IActionResult> Editar(Usuario u){
        if(ModelState.IsValid){
            _context.Usuarios.Update(u);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(u);
    }

    public async Task<IActionResult> Eliminar(int id) {
        //Buscamos en la base de datos
        var usuario = await _context.Usuarios.FindAsync(id);
        //Elimina un objeto del DbSet Usuarios que está dentro del contexto de la base de datos
        _context.Usuarios.Remove(usuario!);
        //Es responsable de guardar los cambios realizados en el contexto de la base de datos de forma asíncrona.       
        await _context.SaveChangesAsync();
        //Nos redirigimos a otra vista
        return RedirectToAction("Index");
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5 text-center">

    <div class="row">
        <div class="col">
            <h1>Welcome</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <a class="btn btn-primary" asp-controller="Usuarios" asp-action="Index">Gestionar
                usuarios</a>
            <a class="btn btn-primary" asp-controller="Productos" asp-action="Index">Gestionar
                productos</a>
        </div>
    </div>
    @* <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p> *@

</div>

Views/Productos/Crear.cshtml
@{
    ViewData["Title"] = "Crear producto";
}
@model Producto

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Crear producto</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <a class="d-flex float-start btn btn-primary" asp-controller="Productos" asp-action="Index">Regresar</a>     
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <form asp-action="Crear" method="post">
                <div class="form-group">
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Descripcion">Descripción:</label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Precio">Precio:</label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Cantidad">Cantidad:</label>
                    <input asp-for="Cantidad" class="form-control" />
                    <span asp-validation-for="Cantidad" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="FechaVencimiento">Fecha de vencimiento:</label>
                    <input asp-for="FechaVencimiento" class="form-control" />
                    <span asp-validation-for="FechaVencimiento" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="ImagenURL">Url de imagen:</label>
                    <input asp-for="ImagenURL" class="form-control" />
                    <span asp-validation-for="ImagenURL" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="UsuarioId">Id del usuario:</label>
                    <input asp-for="UsuarioId" class="form-control" asp-format="{0:yyyy-MM-dd}"/>
                    <span asp-validation-for="UsuarioId" class="text-danger"></span>
                </div>
                <button class="btn btn-primary mt-3">Crear nuevo producto</button>
            </form>
        </div>
    </div>

</div>

Views/Productos/Detalles.cshtml
@{
    ViewData["Title"] = "Detalles";
}

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Detalles del producto</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <a class="d-flex float-start btn btn-primary" asp-controller="Productos" asp-action="Index">Regresar</a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Imagen</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Descripción</th>
                            <th scope="col">Precio</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Fecha de vencimiento</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="align-middle">
                            <th scope="row">@Model.Id</th>
                            <td><img width="100px" src="@Model.ImagenURL" alt="Producto"></td>
                            <td>@Model.Nombre</td>
                            <td style="width: 300px;">@Model.Descripcion</td>
                            <td>$@Model.Precio</td>
                            <td>@Model.Cantidad</td>
                            <td>@Model.FechaVencimiento.ToString("dd/MM/yyyy")</td>   
                            <td>
                                <a class="btn btn-sm btn-warning" asp-controller="Productos" asp-action="Editar" asp-route-id="@Model.Id">Editar</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Productos" asp-action="Eliminar" asp-route-id="@Model.Id">Eliminar</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Productos/Editar.cshtml
@{
    ViewData["Title"] = "Editar producto";
}
@model Producto

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Editar producto</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <a class="d-flex float-start btn btn-primary" asp-controller="Productos" asp-action="Index">Regresar</a>     
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <form asp-action="Editar" method="post">
                <div class="form-group">
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Descripcion">Descripción:</label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Precio">Precio:</label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Cantidad">Cantidad:</label>
                    <input asp-for="Cantidad" class="form-control" />
                    <span asp-validation-for="Cantidad" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="FechaVencimiento">Fecha de vencimiento:</label>
                    <input asp-for="FechaVencimiento" class="form-control" />
                    <span asp-validation-for="FechaVencimiento" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="ImagenURL">Url de imagen:</label>
                    <input asp-for="ImagenURL" class="form-control" />
                    <span asp-validation-for="ImagenURL" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="UsuarioId">Id del usuario:</label>
                    <input asp-for="UsuarioId" class="form-control" />
                    <span asp-validation-for="UsuarioId" class="text-danger"></span>
                </div>
                <button class="btn btn-primary mt-3">Actualizar producto</button>
            </form>
        </div>
    </div>

</div>

Views/Productos/Index.cshtml
@{
    ViewData["Title"] ="Productos";
}

<div class="container mt-5">
              
    <div class="row">
        <div class="col">
            <h1>Lista de productos</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col d-flex justify-content-between">
            <a class="d-flex float-start btn btn-primary" asp-controller="Productos" asp-action="Crear">Crear producto</a>
            <form class="d-flex float-end" asp-action="Index">
                <input name="search" class="form-control me-2" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Imagen</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Descripción</th>
                            <th scope="col">Precio</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Fecha de vencimiento</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var producto in Model) {
                            <tr class="align-middle">
                                <th scope="row">@producto.Id</th>
                                <td><img width="100px" src="@producto.ImagenURL" alt="Producto"></td>
                                <td>@producto.Nombre</td>
                                <td style="width: 300px;">@producto.Descripcion</td>
                                <td>$@producto.Precio</td>
                                <td>@producto.Cantidad</td>
                                <td>@producto.FechaVencimiento.ToString("dd/MM/yyyy")</td>   
                                <td>
                                    <a class="btn btn-sm btn-primary" asp-controller="Productos" asp-action="Detalles" asp-route-id="@producto.Id">Detalles</a>
                                    <a class="btn btn-sm btn-warning" asp-controller="Productos" asp-action="Editar" asp-route-id="@producto.Id">Editar</a>
                                    <a class="btn btn-sm btn-danger" asp-controller="Productos" asp-action="Eliminar" asp-route-id="@producto.Id">Eliminar</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UsuariosProductos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UsuariosProductos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UsuariosProductos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UsuariosProductos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuarios/Crear.cshtml
@{
    ViewData["Title"] = "Crear usuario";
}
@model Usuario

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Crear usuario</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <a class="d-flex float-start btn btn-primary" asp-controller="Usuarios" asp-action="Index">Regresar</a>     
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <form asp-action="Crear" method="post">
                <div class="form-group">
                    <label asp-for="Nombres">Nombres:</label>
                    <input asp-for="Nombres" class="form-control" />
                    <span asp-validation-for="Nombres" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Apellidos">Apellidos:   </label>
                    <input asp-for="Apellidos" class="form-control" />
                    <span asp-validation-for="Apellidos" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Correo">Correo electrónico:</label>
                    <input asp-for="Correo" class="form-control" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Direccion">Dirección:</label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Telefono">Teléfono:</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="FechaNacimiento">Fecha de nacimiento:</label>
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
                <button class="btn btn-primary mt-3">Crear nuevo usuario</button>
            </form>    
        </div>
    </div>

</div>

Views/Usuarios/Detalles.cshtml
@{
    ViewData["Title"] = "Detalles";
}

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Detalles del usuario</h1>   
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <a class="d-flex float-start btn btn-primary" asp-controller="Usuarios" asp-action="Index">Regresar</a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Nombres</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Correo</th>
                            <th scope="col">Dirección</th>
                            <th scope="col">Teléfono</th>
                            <th scope="col">Fecha de nacimiento</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="align-middle">
                            <th scope="row">@Model.Id</th>
                            <td>@Model.Nombres</td>
                            <td>@Model.Apellidos</td>
                            <td>@Model.Correo</td>
                            <td>@Model.Direccion</td>
                            <td>@Model.Telefono</td>
                            <td>@Model.FechaNacimiento.ToString("dd/MM/yyyy")</td>
                            <td>
                                <a class="btn btn-sm btn-warning" asp-controller="Usuarios" asp-action="Editar" asp-route-id="@Model.Id">Editar</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Usuarios" asp-action="Eliminar" asp-route-id="@Model.Id">Eliminar</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Usuarios/Editar.cshtml
@{
    ViewData["Title"] = "Editar usuario";
}
@model Usuario

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Editar usuario</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <a class="d-flex float-start btn btn-primary" asp-controller="Usuarios" asp-action="Index">Regresar</a>     
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <form asp-action="Editar" method="post">
                <div class="form-group">
                    <label asp-for="Nombres">Nombres:</label>
                    <input asp-for="Nombres" class="form-control" />
                    <span asp-validation-for="Nombres" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Apellidos">Apellidos:   </label>
                    <input asp-for="Apellidos" class="form-control" />
                    <span asp-validation-for="Apellidos" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Correo">Correo electrónico:</label>
                    <input asp-for="Correo" class="form-control" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Direccion">Dirección:</label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="Telefono">Teléfono:</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="FechaNacimiento">Fecha de nacimiento:</label>
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
                <button class="btn btn-primary mt-3">Actualizar usuario</button>
            </form>   
        </div>
    </div>

</div>

Views/Usuarios/Index.cshtml
@{
    ViewData["Title"] ="Usuarios";
}

<div class="container mt-5">

    <div class="row">
        <div class="col">
            <h1>Lista de usuarios</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col d-flex justify-content-between">
            <a class="d-flex float-start btn btn-primary" asp-controller="Usuarios" asp-action="Crear">Crear usuario</a>
            <form class="d-flex float-end" asp-action="Index">
                <input class="form-control me-2" name="search" type="search" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Nombres</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Correo</th>
                            <th scope="col">Dirección</th>
                            <th scope="col">Teléfono</th>
                            <th scope="col">Fecha de nacimiento</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var usuario in Model)
                    {
                        <tr class="align-middle">
                            <th scope="row">@usuario.Id</th>
                            <td>@usuario.Nombres</td>
                            <td>@usuario.Apellidos</td>
                            <td>@usuario.Correo</td>
                            <td>@usuario.Direccion</td>
                            <td>@usuario.Telefono</td>
                            <td>@usuario.FechaNacimiento.ToString("dd/MM/yyyy")</td>   
                            <td>
                                <a class="btn btn-sm btn-primary" asp-controller="Usuarios" asp-action="Detalles" asp-route-id="@usuario.Id">Detalles</a>
                                <a class="btn btn-sm btn-warning" asp-controller="Usuarios" asp-action="Editar" asp-route-id="@usuario.Id">Editar</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Usuarios" asp-action="Eliminar" asp-route-id="@usuario.Id">Eliminar</a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>